name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # 监听主分支的推送事件
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6 # 可以选择适合的 Ruby 版本

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # 使用 Gemfile 安装依赖

      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build  # 使用你指定的 Jekyll 版本构建网站

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub token 进行身份验证
          deploy_branch: gh-pages  # 将构建好的文件部署到 gh-pages 分支
